[versions]
# Android
agp = "8.11.2"
appcompat = "1.2.0"
coreKtx = "1.6.0"
desugar = "2.1.4"
gradle = "8.7.0"

# Dairy (FrozenMilk)
mercurial = "2.0.0-beta9"
sloth = "0.2.4"


# FTC
ftc = "11.0.0"

# Kotlin
kotlin = "2.3.0"
kotlinInject = "0.7.2"
ksp = "2.3.4"

# Pedro Pathing
pedroPathing = "2.0.5"
pedroTelemetry = "1.0.0"

# Testing
junit = "4.13.2"
junitExt = "1.3.0"

# FTC Dashboard
ftc-dashboard = "0.2.4+0.5.1"

[libraries]
# Android
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

# Dairy (FrozenMilk)
dairy-mercurial = { module = "dev.frozenmilk.dairy:MercurialFTC", version.ref = "mercurial" }
dairy-sloth = { module = "dev.frozenmilk.dairy:Sloth", version.ref = "sloth" }

# FTC
ftc-blocks = { module = "org.firstinspires.ftc:Blocks", version.ref = "ftc" }
ftc-common = { module = "org.firstinspires.ftc:FtcCommon", version.ref = "ftc" }
ftc-hardware = { module = "org.firstinspires.ftc:Hardware", version.ref = "ftc" }
ftc-inspection = { module = "org.firstinspires.ftc:Inspection", version.ref = "ftc" }
ftc-onbotjava = { module = "org.firstinspires.ftc:OnBotJava", version.ref = "ftc" }
ftc-robotcore = { module = "org.firstinspires.ftc:RobotCore", version.ref = "ftc" }
ftc-robotserver = { module = "org.firstinspires.ftc:RobotServer", version.ref = "ftc" }
ftc-vision = { module = "org.firstinspires.ftc:Vision", version.ref = "ftc" }

# Kotlin
kotlin-inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlin-inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlinInject" }

# Pedro Pathing
pedro-pathing = { module = "com.pedropathing:ftc", version.ref = "pedroPathing" }
pedro-telemetry = { module = "com.pedropathing:telemetry", version.ref = "pedroTelemetry" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junitExt" }

# FTC Dashboard
ftc-dashboard = { module = "com.acmerobotics.slothboard:dashboard", version.ref = "ftc-dashboard" }

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

# Dairy (FrozenMilk)
dairy-sloth-load = { id = "dev.frozenmilk.sinister.sloth.load", version.ref = "sloth" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
