[versions]
agp = "8.11.0"
ftc = "11.0.0"
kotlin = "2.0.21"
junit = "4.13.2"
coreKtx = "1.6.0"
junitVersion = "1.1.5"
appcompat = "1.2.0"

[libraries]
ftc-inspection = { module = "org.firstinspires.ftc:Inspection", version.ref = "ftc" }
ftc-blocks = { module = "org.firstinspires.ftc:Blocks", version.ref = "ftc" }
ftc-robotcore = { module = "org.firstinspires.ftc:RobotCore", version.ref = "ftc" }
ftc-robotserver = { module = "org.firstinspires.ftc:RobotServer", version.ref = "ftc" }
ftc-onbotjava = { module = "org.firstinspires.ftc:OnBotJava", version.ref = "ftc" }
ftc-hardware = { module = "org.firstinspires.ftc:Hardware", version.ref = "ftc" }
ftc-ftccommon = { module = "org.firstinspires.ftc:FtcCommon", version.ref = "ftc" }
ftc-vision = { module = "org.firstinspires.ftc:Vision", version.ref = "ftc" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
